name: app_viajes
description: Aplicación de GPS para viajes
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  geolocator: ^10.1.0   # <--- Actualizar a versión más nueva
  wakelock_plus: ^1.1.0   # <-- Esta es la correcta

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true